[package]
name = "ShellArt"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.5",features = ["derive"]}
opencv = { version = "0.98", features = ["clang-runtime"] }
crossterm = "0.27"
anyhow = "1.0"
rand = "0.8"
eframe = "0.27"
egui = "0.27"
